"""empty message

Revision ID: 9cb1e1feb5d2
Revises: 48456168dda6
Create Date: 2022-08-14 18:15:40.216857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cb1e1feb5d2'
down_revision = '48456168dda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.String(), nullable=False))
    op.add_column('artists', sa.Column('website_link', sa.String(), nullable=False))
    op.drop_column('artists', 'genre')
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'show_start_time')
    op.add_column('venues', sa.Column('genres', sa.String(), nullable=False))
    op.add_column('venues', sa.Column('website_link', sa.String(), nullable=False))
    op.drop_column('venues', 'genre')
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('venues', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('venues', 'website_link')
    op.drop_column('venues', 'genres')
    op.add_column('shows', sa.Column('show_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'start_time')
    op.add_column('artists', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'website_link')
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###
